<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",691,726);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n        	<li><a title=\"[field:typename/]\" href=\"[field:typeurl/]\" \r\n            >[field:typename/]</a></li>\r\n			",1031,1274);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[4]=Array("field","",1473,1502);
$z[4][4]['name']="position";
$z[5]=Array("field","",1577,1596);
$z[5][4]['name']="title";
$z[6]=Array("type","<a href=\"[field:typelink /]\">返回列表</a>",1615,1700);
$z[6][4]['typeid']="0";
$z[6][4]['row']="1";
$z[7]=Array("field","",1722,1774);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y/m/d',@me)";
$z[8]=Array("field","",1858,1876);
$z[8][4]['name']="body";
$z[9]=Array("include","",1923,1960);
$z[9][4]['filename']="footer.htm";

?>