<?php
$z[0]=Array("channelartlist","\r\n	  <li>\r\n		<h2><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></h2>\r\n        <p> \r\n		  {dede:channel type='son'}\r\n		  <a title=\"[field:typename/]\" href=\"[field:typelink/]\">[field:typename/]</a><br>\r\n		  {/dede:channel}\r\n        </p>\r\n      </li>\r\n	  ",1949,2290);
$z[0][4]['typeid']="top";
$z[0][4]['row']="8";
$z[1]=Array("global","",2374,2400);
$z[1][4]['name']="cfg_powerby";

?>