<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",614,649);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n        	<li><a title=\"[field:typename/]\" href=\"[field:typeurl/]\" \r\n            >[field:typename/]</a></li>\r\n			",981,1224);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[4]=Array("field","",1436,1465);
$z[4][4]['name']="typename";
$z[5]=Array("field","",1492,1521);
$z[5][4]['name']="position";
$z[6]=Array("field","",1586,1607);
$z[6][4]['name']="content";
$z[7]=Array("include","",1683,1720);
$z[7][4]['filename']="footer.htm";

?>