<?php
$z[0]=Array("field","(@me==\"\")? @me=\"   class='on'  \":@me=\"\";",548,638);
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channel","\r\n		<li class=\"nav_li\"><a id=\"content\" href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n		",664,928);
$z[1][4]['row']="10";
$z[1][4]['type']="top";
$z[1][4]['col']="1";
$z[1][4]['currentstyle']="<li class='nav_li'><a href='~typelink~' class='on'>~typename~</a></li>";

?>