<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",614,649);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n        	<li><a title=\"[field:typename/]\" href=\"[field:typeurl/]\" \r\n            >[field:typename/]</a></li>\r\n			",954,1197);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[4]=Array("field","",1381,1410);
$z[4][4]['name']="typename";
$z[5]=Array("field","",1437,1466);
$z[5][4]['name']="position";
$z[6]=Array("type","<td class=\"tdbt\"><div>[field:typename /]</div></td>",1628,1714);
$z[6][4]['typeid']="24";
$z[7]=Array("arclist","\r\n				<li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a><span>[[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]]</span></li>\r\n				",1792,2018);
$z[7][4]['row']="5";
$z[7][4]['typeid']="24";
$z[7][4]['titlelen']="60";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("type","<td class=\"tdbt\"><div>[field:typename /]</div></td>",2129,2215);
$z[8][4]['typeid']="25";
$z[9]=Array("arclist","\r\n				<li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a><span>[[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]]</span></li>\r\n				",2293,2519);
$z[9][4]['row']="5";
$z[9][4]['typeid']="25";
$z[9][4]['titlelen']="60";
$z[9][4]['orderby']="pubdate";
$z[10]=Array("include","",2667,2704);
$z[10][4]['filename']="footer.htm";

?>