<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",740,775);
$z[1][4]['filename']="head.htm";
$z[2]=Array("type","<a href=\"[field:typeurl /]\">[field:typename /]</a>",2388,2473);
$z[2][4]['typeid']="15";
$z[3]=Array("arclist","\r\n<dl class=\"[field:global.autoindex runphp='yes']@me = (@me<=1)? \"fl\" : \"fr\";[/field:global.autoindex]\" >\r\n  <dt><a href=\"[field:arcurl /]\" target=\"_blank\"><img src=\"[field:picname/]\" /></a><span></span></dt>\r\n  <dd><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></dd>\r\n</dl>\r\n",2548,2931);
$z[3][4]['row']="2";
$z[3][4]['typeid']="15";
$z[3][4]['titlelen']="60";
$z[3][4]['flag']="p";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("arclist","\r\n        <li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n	",2978,3143);
$z[4][4]['row']="3";
$z[4][4]['typeid']="15";
$z[4][4]['titlelen']="60";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("type","<a href=\"[field:typeurl /]\">[field:typename /]</a>",3216,3301);
$z[5][4]['typeid']="14";
$z[6]=Array("arclist","\r\n        <li><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><a href=\"[field:typeurl /]\" target=\"_blank\">[field:title /]</a></li> \r\n		",3385,3613);
$z[6][4]['row']="7";
$z[6][4]['typeid']="14";
$z[6][4]['titlelen']="80";
$z[6][4]['orderby']="pubdate";
$z[7]=Array("include","",5904,5941);
$z[7][4]['filename']="footer.htm";

?>