<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",614,649);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n        	<li><a title=\"[field:typename/]\" href=\"[field:typeurl/]\" \r\n            >[field:typename/]</a></li>\r\n			",973,1216);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[4]=Array("field","",1401,1430);
$z[4][4]['name']="typename";
$z[5]=Array("field","",1457,1486);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n        <li><a href=\"[field:arcurl/]\" title=\"note\" target=\"_blank\">[field:title/]</a><span>[[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]]</span></li>\r\n		",1608,1817);
$z[6][4]['pagesize']="10";
$z[6][4]['infolen']="150";
$z[7]=Array("pagelist","",1887,1942);
$z[7][4]['istitem']="index,pre,next,";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2003,2040);
$z[8][4]['filename']="footer.htm";

?>