<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",980,1015);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n        	<li><a title=\"[field:typename/]\" href=\"[field:typeurl/]\" \r\n            >[field:typename/]</a></li>\r\n			",1320,1563);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[4]=Array("field","",1748,1777);
$z[4][4]['name']="typename";
$z[5]=Array("field","",1804,1833);
$z[5][4]['name']="position";
$z[6]=Array("include","",4386,4423);
$z[6][4]['filename']="footer.htm";

?>